### PR TITLE
Fix build on EL7.4

### PR DESCRIPTION
**Pull request by ambakshi**
This fixes the build for EL 7.4 where I was seeing the following error:

DKMS make.log for ena-1.2.0 for kernel 3.10.0-693.el7.x86_64 (x86_64)
Thu Aug 10 23:06:10 UTC 2017
make: Entering directory `/var/lib/dkms/ena/1.2.0/build/kernel/linux/ena'
make -C /lib/modules/3.10.0-693.el7.x86_64/build M=/var/lib/dkms/ena/1.2.0/build/kernel/linux/ena modules
make[1]: Entering directory `/usr/src/kernels/3.10.0-693.el7.x86_64'
make[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
  CC [M]  /var/lib/dkms/ena/1.2.0/build/kernel/linux/ena/ena_netdev.o
In file included from /var/lib/dkms/ena/1.2.0/build/kernel/linux/ena/ena_netdev.h:44:0,
                 from /var/lib/dkms/ena/1.2.0/build/kernel/linux/ena/ena_netdev.c:53:
/var/lib/dkms/ena/1.2.0/build/kernel/linux/ena/kcompat.h:424:6: error: nested redefinition of ‘enum pkt_hash_types’
 enum pkt_hash_types {
      ^
compilation terminated due to -Wfatal-errors.
make[2]: *** [/var/lib/dkms/ena/1.2.0/build/kernel/linux/ena/ena_netdev.o] Error 1
make[1]: *** [_module_/var/lib/dkms/ena/1.2.0/build/kernel/linux/ena] Error 2
make[1]: Leaving directory `/usr/src/kernels/3.10.0-693.el7.x86_64'
make: *** [all] Error 2
make: Leaving directory `/var/lib/dkms/ena/1.2.0/build/kernel/linux/ena'

### CODE REVIEW

**Comment by netanelbelgazal** [comment]
Thank you for the fix.
I'll make sure it doesn't break anything else and merge it.
